version: '3.8'

services:
  nats-server:
    image: nats:2.10-alpine
    container_name: nats-server
    # THAY ĐỔI LỆNH CHẠY: Yêu cầu NATS nạp file cấu hình
    command: "-c /etc/nats/nats-server.conf"
    volumes:
      # MOUNT FILE: Ánh xạ file từ GitHub vào trong Container
      - ./nats_server_sample.conf:/etc/nats/nats-server.conf
    networks:
      - coolify

  # 2. Cơ sở dữ liệu MariaDB
  plugnmeet-db:
    image: mariadb:10.11
    container_name: plugnmeet-db
    environment:
      MYSQL_ROOT_PASSWORD: "thanhnguyen_db_password"
      MYSQL_DATABASE: "plugnmeet"
    volumes:
      - plugnmeet_db_data:/var/lib/mysql
    networks:
      - coolify

  # 3. Backend API
  plugnmeet-server:
    # Ở đây chúng ta yêu cầu Coolify build từ Dockerfile trên Github thay vì kéo image thuần
    build: 
      context: https://github.com/nguyennhanduc-91/nextgen-meet-plugnmeet-server.git#main
    container_name: plugnmeet-server
    depends_on:
      - nats-server
      - plugnmeet-db
    networks:
      - coolify

networks:
  coolify:
    external: true

volumes:
  plugnmeet_db_data:
